version: "3.5"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.7.0.0/24

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /media/InternalMedia:/media
    restart: unless-stopped
    hostname: jellyfin
    networks:
      private_network:
        ipv4_address: 10.7.0.100
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://cristian-mihai.go.ro
